#!/usr/bin/python3

from prometheus_async import aio
from prometheus_client import Gauge
import asyncio
import json
import requests
import sys
import time

ENDPOINT = "https://soulless.aa.net.uk/info.cgi"


def get_remaining():
    response = json.loads(
        requests.get(
            ENDPOINT, headers={"Accept": "application/json"}
        ).content.decode("UTF-8")
    )
    return response["quota_remaining"]


g = Gauge("aa_quota_remaining_bytes", "AAISP quota remaining (bytes)")
g.set_function(get_remaining)

aio.web.start_http_server_in_thread(port=8000)
asyncio.get_event_loop().run_forever()
